services:
  frontend:
    container_name: todolist-frontend
    image: todolist-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5040:5040"
    environment:
      - NODE_ENV=test
    #restart: unless-stopped
#    depends_on:
#- mongo
#    networks:
#      - todolist-net
#
#networks:
#  todolist-net:
#    name: todolist-net
#    driver: bridge
