version: '3.8'

services:
  frontend:
    container_name: todolist-frontend
    image: todolist/frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=staging
    #restart: unless-stopped
    depends_on:
      - mongo
