services:
  mongo:
    extends:
      file: db-mongo/docker-compose.yaml
      service: mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - todolist-net

  elasticsearch:
    extends:
      file: ./elk-elasticsearch/docker-compose.yaml
      service: elasticsearch
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - todolist-net
      
  kibana:
    extends:
      file: ./elk-kibana/docker-compose.yaml
      service: kibana
    networks:
      - todolist-net
      
  todolist-frontend:
    extends:
      file: ./frontend/docker-compose.yaml
      service: todolist-frontend
    networks:
      - todolist-net
  
  todolist-backend:
    extends:
      file: ./backend/docker-compose.yaml
      service: todolist-backend
    networks:
      - todolist-net

volumes:
  mongo-data:
    name: mongo-data
  es-data:
    name: es-data

networks:
  todolist-net:
    name: todolist-net
    driver: bridge
