services:
  kibana:
    container_name: kibana
    image:  kibana:7.17.9
    ports:
      - "9201:9201"
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    depends_on:
      - elasticsearch
