services:
  kibana:
    container_name: kibana
    image:  kibana:7.17.9
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
      SERVER_PUBLICBASEURL: "http://kibana.ermalaliraj.com"
    depends_on:
      - elasticsearch
