services:
  kibana:
    container_name: kibana
    image:  kibana:7.17.9
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
      SERVER_PUBLICBASEURL: "http://todolist.ermalaliraj.com:5601"
#    depends_on:
#      - elasticsearch
    networks:
      - todolist-net

networks:
  todolist-net:
    name: todolist-net
    driver: bridge