services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.17.9
    ports:
      - "5600:5600"
    environment:
      - discovery.type=single-node
    volumes:
      - es-data:/data/elasticsearch

volumes:
  es-data: