services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.17.9
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
    volumes:
      - es-data:/usr/share/elasticsearch/data

volumes:
  es-data: