services:
  mongo:
    container_name: mongo
    image: mongo:8.0.9
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: todolist
      MONGO_INITDB_ROOT_PASSWORD: todolist
    volumes:
      - mongo-data:/data/db
    networks:
      - todolist-net

volumes:
  mongo-data:
    name: mongo-data
    
networks:
  todolist-net:
    name: todolist-net
    driver: bridge