export const API_URL = process.env.NEXT_PUBLIC_API_URL;
export const MOCK_API_ENABLED = process.env.NEXT_PUBLIC_MOCK_API_ENABLED;
export const MOCK_API_TODOLIST_ENABLED = process.env.NEXT_PUBLIC_MOCK_API_TODOLIST_ENABLED;
